title: COVID-19 Data Analytics
description: Thank you for visiting our COVID-19 page. This website provides information about our research on COVID-19 data visualization, modeling and mitigation policies.
sitename: COVID-19 Data Analytics
baseurl: '/covid-19'

sass:
  sass_dir: /assets/_sass
  style: :compressed

collections:
  features:
    output: true
    permalink: /feature/:path/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME